#!/bin/bash

# SafeBrowser Frontend Environment Setup Script
# This script helps you quickly configure the frontend to connect to your backend

set -e

echo "🔧 SafeBrowser Frontend Environment Setup"
echo "=========================================="

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

print_status() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

print_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Check if .env already exists
if [ -f ".env" ]; then
    print_warning ".env file already exists!"
    read -p "Do you want to overwrite it? (y/N): " overwrite
    if [[ ! $overwrite =~ ^[Yy]$ ]]; then
        print_status "Keeping existing .env file."
        exit 0
    fi
fi

# Get backend configuration from user
echo ""
print_status "Please provide your backend service configuration:"
echo ""

read -p "Backend host (default: localhost): " backend_host
backend_host=${backend_host:-localhost}

read -p "Backend port (default: 3000): " backend_port
backend_port=${backend_port:-3000}

# Validate port is a number
if ! [[ "$backend_port" =~ ^[0-9]+$ ]]; then
    print_error "Port must be a number!"
    exit 1
fi

# Create .env file
print_status "Creating .env file..."

cat > .env << EOF
# SafeBrowser Frontend Environment Configuration
# Generated by setup-env.sh

# ===========================================
# Backend API Configuration
# ===========================================
REACT_APP_API_URL=http://${backend_host}:${backend_port}/api/v1
REACT_APP_AUTH_URL=http://${backend_host}:${backend_port}/api/auth
REACT_APP_WS_URL=ws://${backend_host}:${backend_port}

# ===========================================
# AI Provider API Keys (Optional)
# ===========================================
REACT_APP_HUGGINGFACE_API_KEY=your_huggingface_api_key_here
REACT_APP_GEMINI_API_KEY=your_gemini_api_key_here
REACT_APP_COHERE_API_KEY=your_cohere_api_key_here
REACT_APP_CLAUDE_API_KEY=your_claude_api_key_here

# ===========================================
# Web3 Configuration
# ===========================================
REACT_APP_DEFAULT_CHAIN_ID=1
REACT_APP_SUPPORTED_CHAINS=1,137,56,42161

# ===========================================
# Feature Flags
# ===========================================
REACT_APP_ENABLE_AI_CHAT=true
REACT_APP_ENABLE_DAPP_STORE=true
REACT_APP_ENABLE_PORTFOLIO=true
REACT_APP_ENABLE_VAULT=true
REACT_APP_DEBUG=true
REACT_APP_USE_REAL_API=true

# ===========================================
# Development Configuration
# ===========================================
WDS_SOCKET_HOST=localhost
WDS_SOCKET_PORT=3001
FAST_REFRESH=true
EOF

print_success ".env file created successfully!"

echo ""
print_status "Configuration Summary:"
print_status "  - Backend API URL: http://${backend_host}:${backend_port}/api/v1"
print_status "  - Auth URL: http://${backend_host}:${backend_port}/api/auth"
print_status "  - WebSocket URL: ws://${backend_host}:${backend_port}"

echo ""
print_warning "Next steps:"
print_warning "1. Make sure your backend service is running on ${backend_host}:${backend_port}"
print_warning "2. Test the connection: curl http://${backend_host}:${backend_port}/api/auth/register"
print_warning "3. Restart your frontend development server to pick up the new environment variables"
print_warning "4. (Optional) Add your AI API keys to the .env file"

echo ""
print_success "Environment setup complete! 🎉"


