#!/bin/bash

# BitAI Frontend Environment Setup Script
# This script helps you quickly configure the frontend to connect to your backend
#
# Usage:
#   ./scripts/setup-env.sh
#   BACKEND_HOST=api.example.com BACKEND_PORT=8080 ./scripts/setup-env.sh
#
# Environment Variables:
#   BACKEND_HOST: Backend hostname or IP (default: localhost)
#   BACKEND_PORT: Backend port (default: 3000)
#   NON_INTERACTIVE: Set to 1 to skip interactive prompts

set -euo pipefail  # Exit on error, undefined vars, and pipe failures

echo "🔧 BitAI Frontend Environment Setup"
echo "=========================================="

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

print_status() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

print_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Validate port number (1-65535)
validate_port() {
    local port=$1
    if ! [[ "$port" =~ ^[0-9]+$ ]]; then
        print_error "Port must be a number"
        return 1
    fi
    if [ "$port" -lt 1 ] || [ "$port" -gt 65535 ]; then
        print_error "Port must be between 1 and 65535"
        return 1
    fi
    return 0
}

# Validate host (IP or hostname)
validate_host() {
    local host=$1
    # Check if it's a valid IP address
    if [[ "$host" =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
        # Validate IP octets
        IFS='.' read -ra ADDR <<< "$host"
        for i in "${ADDR[@]}"; do
            if [ "$i" -gt 255 ]; then
                print_error "Invalid IP address: $host"
                return 1
            fi
        done
        return 0
    fi
    # Check if it's a valid hostname (alphanumeric, dots, hyphens)
    if [[ "$host" =~ ^[a-zA-Z0-9.-]+$ ]]; then
        return 0
    fi
    print_error "Invalid host format: $host (must be IP address or hostname)"
    return 1
}

# Check if .env already exists
if [ -f ".env" ]; then
    print_warning ".env file already exists!"
    
    if [ "${NON_INTERACTIVE:-0}" = "1" ]; then
        # Non-interactive mode: backup existing file
        BACKUP_FILE=".env.backup.$(date +%Y%m%d_%H%M%S)"
        print_status "Backing up existing .env to $BACKUP_FILE"
        cp .env "$BACKUP_FILE"
    else
    read -p "Do you want to overwrite it? (y/N): " overwrite
    if [[ ! $overwrite =~ ^[Yy]$ ]]; then
        print_status "Keeping existing .env file."
        exit 0
        fi
        # Backup existing file
        BACKUP_FILE=".env.backup.$(date +%Y%m%d_%H%M%S)"
        print_status "Backing up existing .env to $BACKUP_FILE"
        cp .env "$BACKUP_FILE"
    fi
fi

# Get backend configuration from user
if [ "${NON_INTERACTIVE:-0}" = "1" ]; then
    # Non-interactive mode: use environment variables
    backend_host="${BACKEND_HOST:-localhost}"
    backend_port="${BACKEND_PORT:-3000}"
else
echo ""
print_status "Please provide your backend service configuration:"
echo ""

read -p "Backend host (default: localhost): " backend_host
backend_host=${backend_host:-localhost}

read -p "Backend port (default: 3000): " backend_port
backend_port=${backend_port:-3000}
fi

# Validate host
if ! validate_host "$backend_host"; then
    exit 1
fi

# Validate port
if ! validate_port "$backend_port"; then
    exit 1
fi

# Create .env file
print_status "Creating .env file..."

# Use temporary file for atomic write
TEMP_ENV=$(mktemp)
trap "rm -f $TEMP_ENV" EXIT

cat > "$TEMP_ENV" << EOF
# BitAI Frontend Environment Configuration
# Generated by setup-env.sh

# ===========================================
# Backend API Configuration
# ===========================================
REACT_APP_API_URL=http://${backend_host}:${backend_port}/api/v1
REACT_APP_AUTH_URL=http://${backend_host}:${backend_port}/api/auth
REACT_APP_WS_URL=ws://${backend_host}:${backend_port}

# ===========================================
# AI Provider API Keys (Optional)
# ===========================================
REACT_APP_HUGGINGFACE_API_KEY=your_huggingface_api_key_here
REACT_APP_GEMINI_API_KEY=your_gemini_api_key_here
REACT_APP_COHERE_API_KEY=your_cohere_api_key_here
REACT_APP_CLAUDE_API_KEY=your_claude_api_key_here

# ===========================================
# Web3 Configuration
# ===========================================
REACT_APP_DEFAULT_CHAIN_ID=1
REACT_APP_SUPPORTED_CHAINS=1,137,56,42161

# ===========================================
# Feature Flags
# ===========================================
REACT_APP_ENABLE_AI_CHAT=true
REACT_APP_ENABLE_DAPP_STORE=true
REACT_APP_ENABLE_PORTFOLIO=true
REACT_APP_ENABLE_VAULT=true
REACT_APP_DEBUG=true
REACT_APP_USE_REAL_API=true

# ===========================================
# Development Configuration
# ===========================================
WDS_SOCKET_HOST=localhost
WDS_SOCKET_PORT=3001
FAST_REFRESH=true
EOF

# Move temporary file to .env (atomic operation)
if mv "$TEMP_ENV" .env; then
print_success ".env file created successfully!"
else
    print_error "Failed to create .env file."
    exit 1
fi

# Verify .env file was created and is readable
if [ ! -r ".env" ]; then
    print_error ".env file is not readable."
    exit 1
fi

echo ""
print_status "Configuration Summary:"
print_status "  - Backend API URL: http://${backend_host}:${backend_port}/api/v1"
print_status "  - Auth URL: http://${backend_host}:${backend_port}/api/auth"
print_status "  - WebSocket URL: ws://${backend_host}:${backend_port}"

echo ""
print_warning "Next steps:"
print_warning "1. Make sure your backend service is running on ${backend_host}:${backend_port}"
print_warning "2. Test the connection: curl http://${backend_host}:${backend_port}/api/auth/register"
print_warning "3. Restart your frontend development server to pick up the new environment variables"
print_warning "4. (Optional) Add your AI API keys to the .env file"

echo ""
print_success "Environment setup complete! 🎉"


